# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

inhibit_all_warnings!

target 'TzlBasicProject' do
    
    pod 'BmobSDK'
    pod 'Masonry'  #布局
    pod 'SDWebImage'  #为系统原生UI类，提供网络图片功能
    pod 'MJRefresh'   #滚定页面的刷新UI
    pod 'MJExtension'
    
    pod 'AFNetworking'  #网络请求
    pod 'BlocksKit'  #修改target+selector 和 delegate为block方式
    pod 'CocoaLumberjack'  #替代系统原生NSLog
    
    pod 'MBProgressHUD'  #弹出提示UI
    pod 'SVProgressHUD'
    
    pod 'TPKeyboardAvoiding'
    pod 'MLTransition'  #修复自定义导航栏左上角按钮时导致的右滑返回失效
    
    pod 'YYKit'  #数据解析
    
    pod 'UITableView+FDTemplateLayoutCell'  #高效带缓存的cell高度自动计算
    
    pod 'iCarousel'  #3D切换
    pod 'WMPageController'  #视图切换
    
    pod 'MWPhotoBrowser' #图片浏览
    
    pod 'RESideMenu'  #侧边栏
    
    pod 'PSCollectionView'
    
end

